-- Create a unique index on (type, entryId) for contest_win transactions
-- This prevents duplicate contest_win transactions for the same entry
-- Note: This migration has been moved to a later migration after Transaction table creation
-- The index creation is now handled in a subsequent migration